Redesign database
Diary-SPO/vk-bot pull request #18
Opened 2023-10-05 16:26 UTC by Zamelane

For a new base, a new design (u_u)

2023-10-05 16:28 UTC, scffs commented on src/dblogic/login.ts
> +    const SPO     = res.data.tenants[res.data.tenantName].settings.organization
Что за отступы?

2023-10-05 16:31 UTC, scffs commented on src/types/database/index.ts
> +  interface Id {
Удалить

2023-10-05 16:31 UTC, scffs commented on src/types/database/index.ts
> +  export interface IGetGroup extends Group, Id {}
В следствии удаления Id избавиться от наследования

2023-10-05 16:32 UTC, scffs commented on src/dblogic/login.ts
> +import { type DiaryUser, type VKUser, type SPO as SPO_type, type Group } from '@types/database'
Не надо использовать `_`

2023-10-05 16:32 UTC, scffs requested changes
Исправить мелкие недочёты

2023-10-05 16:46 UTC, scffs requested changes

2023-10-05 16:46 UTC, scffs commented on src/types/index.ts
>  import { type IContext, type ISessionContext } from '@vk-io/session'
Добавь тут пж export * from './database' и поправь импорты

2023-10-06 08:13 UTC, Zamelane commented on src/types/index.ts
>  import { type IContext, type ISessionContext } from '@vk-io/session'
А зачем в database пихать ?... Там же свои типы

2023-10-06 08:59 UTC, scffs approved these changes

2023-10-06 09:00 UTC, merged