3 feature получение расписания
Diary-SPO/vk-bot pull request #22
Opened 2023-10-07 05:44 UTC by Zamelane

2023-10-07 06:49 UTC, scffs requested changes
Сначала пофиксить ошибки, а потом можешь дописывать логику

2023-10-07 06:49 UTC, scffs commented on src/types/database/index.ts
> +// TODO: привести все к одному типу likeThisStyle (ВЕЗДЕ!)
Стиль нейминга поменять

2023-10-07 06:49 UTC, scffs commented on src/init/bot.ts
> +  token: String(TOKEN),
Зачем?

2023-10-07 06:49 UTC, scffs commented on src/dblogic/login.ts
> +    // Здесь в итоге, после обновления или вставке, будут актуальные данные
Удалить коммент

2023-10-07 06:49 UTC, scffs commented on src/dblogic/login.ts
> +      directorname: SPO.directorName
Стиль нейминга поменять

2023-10-07 06:51 UTC, scffs commented
Сделал PR `Draft` т.к. к ревью ещё не готово

2023-10-07 09:40 UTC, Zamelane commented on src/dblogic/auth.ts
> +      .where(`"id" = ${user.diaryId}`)
Вот тут, наверное, зря обернул. Толку 0 от этого

2023-10-07 09:54 UTC, scffs commented on src/dblogic/auth.ts
> +      .where(`"id" = ${user.diaryId}`)
Проверь

2023-10-07 14:11 UTC, scffs commented
Поправить нейминг 
https://github.com/Diary-SPO/vk-bot/blob/242ac214cb084b6cded225c2be6b29e7665eaacf/src/scenes/home/index.ts#L18

2023-10-07 17:42 UTC, scffs requested changes

2023-10-07 17:42 UTC, scffs commented on src/dblogic/schedule.ts
> +export const schedule = async (diaryUser: DiaryUser, date: Date, localCache: boolean, cookie: string): Promise<unknown> => {
Почему `unknown`?

2023-10-07 17:42 UTC, scffs commented on src/dblogic/schedule.ts
> +  else return getScheduleFromNetworkCity(diaryUser, date, cookie)
Давай всё-таки использовать {}

2023-10-07 17:42 UTC, scffs commented on src/dblogic/tables/schedule/getTeacherId.ts
> +        return teacherExisting.id
Почему 4 пробела?

2023-10-07 17:42 UTC, scffs commented on src/dblogic/tables/schedule/index.ts
> +
Не забывай линтером проходить

2023-10-07 17:42 UTC, scffs commented on src/dblogic/tables/schedule/save.ts
> +                subjectName: lesson?.name ?? '???',
lesson?.name разве может не придти? Зачем `?`?

2023-10-07 17:42 UTC, scffs commented on src/dblogic/tables/schedule/save.ts
> +                if (scheduleInsert === null) throw new Error('Error insert schedule')
{}

2023-10-07 17:42 UTC, scffs commented on src/dblogic/tables/schedule/save.ts
> +                else throw new Error('Error get id from update row')
{}

2023-10-07 17:42 UTC, scffs commented on src/dblogic/tables/schedule/save.ts
> +        if (scheduleIdsActualy.length > 0)
{}

2023-10-07 17:42 UTC, scffs commented on src/types/database/index.ts
>    teacherId: number | null
Почему стало `?`

Если не ошибаюсь, то `id?: smth` означает, что поля может не быть

2023-10-11 14:01 UTC, scffs requested changes

2023-10-11 14:01 UTC, scffs commented on src/dblogic/tables/schedule/save.ts
>        else throw new Error('Error get id from insert row')
Переделай пж
```js
if (!scheduleInsert.id) {
   throw new Error('Error get id from insert row')
}
scheduleIdsActualy.push(scheduleInsert.id)
thisSchedule.id = scheduleInsert.id
thisSchedule.groupId = scheduleInsert.groupId
```

2023-10-11 14:01 UTC, scffs commented on src/dblogic/tables/schedule/save.ts
>        else throw new Error('Error get id from update row')
Тоже самое, что и коментом выше

2023-10-11 14:03 UTC, Zamelane commented on src/dblogic/tables/gradebook/index.ts
> +    const gradebookQueryBuilder = createQueryBuilder<GradebookDB>().from('gradebook').select('*').where(`"scheduleId" = '${actualGradebook.scheduleId}'`)
Ок

2023-10-11 14:04 UTC, Zamelane commented on src/dblogic/tables/gradebook/index.ts
> +        if (existingThemes) {
Да, это чисто чтобы из базы удалить старые записи

2023-10-11 14:04 UTC, Zamelane commented on src/dblogic/tables/gradebook/index.ts
> +    return
Кто ?

2023-10-11 14:06 UTC, Zamelane commented on src/dblogic/tables/gradebook/index.ts
> +    return
А, ретюрн... У меня тут прсото уже код написан на строке :)
P.S. Нет, не нужен

2023-10-11 14:14 UTC, scffs commented on src/dblogic/tables/gradebook/index.ts
> +    return
Тогда удалишь и ок

2023-10-11 14:50 UTC, Zamelane commented on src/dblogic/tables/schedule/save.ts
> +import { gradebookSave } from '..'
Ой, это автоматический импорт :)

2023-10-14 18:35 UTC, scffs commented
Если надо будет менять README.md и тд, то создай отдельное issue для этого

2023-10-14 19:01 UTC, scffs requested changes

2023-10-14 19:02 UTC, scffs reviewed
Не забывай про ESLint ошибки

2023-10-15 14:06 UTC, scffs requested changes

2023-10-15 14:06 UTC, scffs commented on src/dblogic/tables/gradebook/index.ts
> +    .where(`"scheduleId" = '${sc.id}'`)
Лишний пробел

2023-10-15 17:15 UTC, Zamelane commented on src/dblogic/schedule.ts
> +  return await getScheduleFromNetworkCity(diaryUser, date, cookie)
Так это пустышка же )

2023-10-24 13:22 UTC, scffs commented on src/dblogic/interactiveMethods/scheduleController.ts
> +}`
Такое ощущение, что текст можно куда-то вынести для красоты

2023-10-26 05:43 UTC, Zamelane commented on src/dblogic/tables/schedule/save.ts
> +                subjectName: lesson?.name ?? '???',
Может не быть объекта, т.к. в diary-shared > src > types.ts > Lesson > name может быть string | null. Вопросы не ко мне :)

2023-10-26 05:46 UTC, Zamelane commented on src/types/database/index.ts
>    teacherId: number | null
По умолчанию может не быть, когда мы только определяем/готовим к вставке. А вот после тогда как строка вставлена/обновлена в базу (-е), мы уже определяем эти поля

2023-10-26 05:49 UTC, Zamelane commented on src/types/database/index.ts
>    teacherId: number | null
ПЖ, сделай экспорт Teacher в diary-shared, чтобы он был доступен не только локально

2023-10-26 05:51 UTC, Zamelane commented on src/dblogic/tables/gradebook/index.ts
> +    if (!sc?.id || !sc.groupId) return
Точно стоит оборачивать? Там же маленькое условие...

2023-10-26 05:55 UTC, Zamelane commented on src/dblogic/interactiveMethods/scheduleController.ts
> +const days = ['⛱ Воскресенье', '🚀 Понедельник', '👓 Вторник', '🎭 Среда', '🎈 Четверг', '✨ Пятница', '🛵 Суббота']
Ага, думаю было бы хорошо

2023-10-26 05:56 UTC, Zamelane commented on src/dblogic/interactiveMethods/scheduleController.ts
> +}`
Ок

2023-10-26 06:06 UTC, scffs commented on src/dblogic/tables/schedule/save.ts
> +                subjectName: lesson?.name ?? '???',
Разве тогда не надо писать `lesson.name ?? '???'` ?

2023-10-26 06:07 UTC, scffs commented on src/types/database/index.ts
>    teacherId: number | null
Создай пж issue в diary-shared.. Или можешь сам поправить и сделать PR

2023-10-26 06:07 UTC, scffs commented on src/dblogic/tables/gradebook/index.ts
> +    if (!sc?.id || !sc.groupId) return
Гуд, давай оставим

2023-10-26 07:31 UTC, scffs requested changes

2023-10-26 07:31 UTC, scffs commented on src/dblogic/interactiveMethods/scheduleController.ts
> +import { selectedDayResponse } from './scheduleController/'
Зачем последний слеш?

2023-10-26 07:31 UTC, scffs commented on src/dblogic/interactiveMethods/scheduleController/messagesFormatted.ts
> +}
Может это также вынести в `./formatted`?

2023-10-26 07:41 UTC, Zamelane commented on src/dblogic/interactiveMethods/scheduleController.ts
> +import { selectedDayResponse } from './scheduleController/'
Чтобы точно сказать, что брать из папки, а не файла

2023-10-26 07:41 UTC, Zamelane commented on src/dblogic/interactiveMethods/scheduleController/messagesFormatted.ts
> +}
Ок

2023-10-26 08:51 UTC, scffs commented on src/dblogic/interactiveMethods/scheduleController.ts
> +import { selectedDayResponse } from './scheduleController/'
не понял, мы нигде не писали раньше так

2023-10-26 14:37 UTC, Zamelane commented on src/dblogic/interactiveMethods/scheduleController.ts
> +import { selectedDayResponse } from './scheduleController/'
Переименовал

2023-10-26 16:17 UTC, merged