Registration from database
Diary-SPO/vk-bot pull request #7
Opened 2023-09-27 16:10 UTC by Zamelane

What to do when there is a lot to do? That's right, finish the registration of the bot! ᕙ(⇀‸↼‶)ᕗ

2023-09-27 18:14 UTC, scffs commented on src/config/index.ts
> +export const ENCRYPT_KEY = Bun.env?.ENCRYPT_KEY ?? 'ENCRYPT_KEY!!!!!' // 12, 24 или 32 символа
Нельзя тут возвращать undefined или пустую строку?

2023-09-27 18:14 UTC, scffs commented on src/dblogic/auth.ts
> +import crypto from '@src/dblogic/crypto.ts'
Давай `.ts` не писать

2023-09-27 18:15 UTC, scffs commented on src/dblogic/auth.ts
> +    } else {
Неужели эта строчка точно нужна? давай сделаем наборот, сделаем `if ` на условие, где будем возвращать false, а уже вне `if` напишем `return true`

2023-09-27 18:17 UTC, scffs commented on src/dblogic/login.ts
> +import { type person } from '@src/types/database/person.ts'
Типы с большой буквы, и у нас уже есть `diary-shared`, а в нём `UserData` со всеми типами

2023-09-28 05:11 UTC, Zamelane commented on src/config/index.ts
> +export const ENCRYPT_KEY = Bun.env?.ENCRYPT_KEY ?? 'ENCRYPT_KEY!!!!!' // 12, 24 или 32 символа
Пустая строка всё равно будет считаться паролем, а undefinde поломает всё... Нужно чтобы был хоть какой-то ключик

2023-09-28 05:12 UTC, Zamelane commented on src/config/index.ts
> +export const ENCRYPT_KEY = Bun.env?.ENCRYPT_KEY ?? 'ENCRYPT_KEY!!!!!' // 12, 24 или 32 символа
Глянул. Пустую строку нельзя

2023-09-28 05:53 UTC, scffs commented on src/config/index.ts
> +export const ENCRYPT_KEY = Bun.env?.ENCRYPT_KEY ?? 'ENCRYPT_KEY!!!!!' // 12, 24 или 32 символа
Что именно поломает undefined?

2023-09-28 10:28 UTC, scffs commented on package.json
> +    "aes-js": "^3.1.2",
Можем отказаться от `aes-js` в пользу стандартного `crypto`

2023-09-28 10:28 UTC, scffs commented on src/dblogic/contexter.ts
> +const contexts: any = []
Избавиться от `any ` по возможности

2023-09-28 10:28 UTC, scffs commented on src/dblogic/crypto.ts
> +}
Проверить логику шифрования/дешифрования

2023-09-28 10:28 UTC, scffs commented on src/init/db.ts
> +export { UserVK, UserDnevnik }
Не хотим ли мы везде `Dnevnik` заменить на `Diary` ?))

2023-09-28 10:28 UTC, scffs commented on src/dblogic/disauth.ts
> +}
Было бы лучше переименовать в `logout`

2023-09-28 10:28 UTC, scffs commented on src/init/db.ts
> +const UserVK = mongoose.model('uservks', new Schema({
Указать дженерик для схемы. пример есть на седьмой строке

2023-09-28 10:28 UTC, scffs commented on src/dblogic/disauth.ts
> +}
Дополнительно улучшить функционал логаута, без доп. коллекции

2023-09-28 10:28 UTC, scffs commented on src/types/index.ts
>  }
Подумать над CustomContext, нужен ли он или есть нормальная замена

2023-09-29 10:01 UTC, scffs commented on package.json
> +    "aes-js": "^3.1.2",
Также желательно после удаления посмотреть способ очистки bun.lockb от лишних зависимостей, если автоматом не делается

2023-09-29 17:39 UTC, scffs commented on src/scenes/schedule/index.ts
> +])
Давай всю логику этого файла уже напишешь в другом PR, в этом, пожалуйста, пофикси все комменты касательно регистрации/авторизации

Возможно здесь же сразу реализовать токены, как обговаривали ранее

2023-09-29 17:39 UTC, scffs requested changes
Оставил комменты

2023-09-30 09:56 UTC, scffs requested changes
Надо линтером пройтись

2023-09-30 10:08 UTC, scffs approved these changes

2023-09-30 10:08 UTC, merged